license="All rights reserved"
loaderVersion="[31,)"
modLoader="javafml"
showAsResourcePack=true

[[mods]]
modId="csc450project"
version="1.1"
displayName="Player Behavior Tracker"
displayURL="minecraftforge.net"
credits="Thanks to Eric Dorshimer, Justin Balderson, Max Groover, Noah Gilgo, Taylor Dalrymple, Carl Blackmon (Tester), Dr. Vetter, and Dr. Cariveau"
authors="Colby Kopec"
description='''A University of North Carolina Wilmington CSC-450 Software Engineering Project



Special thanks to Dr. Vetter and Dr. Cariveau.'''


  [[dependencies.examplemod]]
	modId="forge"
	mandatory=true
	versionRange="[31,)"
	ordering="NONE"
	side="BOTH"

  [[dependencies.examplemod]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.3]"
	ordering="NONE"
	side="BOTH"